import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';

const PrivacyPage: React.FC = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-darkforest-50 via-earth-50 to-darkforest-100">
      {/* Header */}
      <div className="bg-white shadow-sm border-b border-gray-200">
        <div className="container mx-auto px-4 py-4">
          <Link to="/consent" className="inline-flex items-center text-darkforest-700 hover:text-darkforest-800">
            <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            Back to Consent
          </Link>
        </div>
      </div>

      {/* Main Content */}
      <div className="container mx-auto px-4 py-12">
        <motion.div
          className="max-w-4xl mx-auto"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <div className="card p-8">
            <h1 className="text-3xl font-bold text-gray-900 mb-6">Privacy & Disclaimer Policy</h1>
            
            <div className="prose prose-lg max-w-none text-gray-700">
              <p className="text-lg mb-6">
                <strong>Effective Date:</strong> July 18, 2025
              </p>

              <p className="mb-6">
                This Privacy & Disclaimer Policy ("Policy") governs the use of the A(rDx)HD Platform ("Platform," "we," "our," or "us") and outlines how we collect, use, protect, and disclose user information. This Policy also clarifies the educational and non-diagnostic nature of the services provided. By accessing or using the Platform, you agree to the terms of this Policy.
              </p>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">1. Educational Purpose Only – No Medical Advice or Diagnosis</h2>
                <div className="bg-red-50 border border-red-200 p-4 rounded-lg mb-4">
                  <p className="text-red-800">
                    <strong>Important Disclaimer:</strong> All content, games, assessments, and recommendations provided through this Platform are intended solely for educational and informational purposes.
                  </p>
                </div>
                <ul className="list-disc list-inside space-y-2">
                  <li>We do not provide medical or psychological diagnoses. The Platform is not a medical device and is not approved by any regulatory body (including the FDA or similar authorities).</li>
                  <li>No result generated by this Platform should be interpreted as a diagnosis of Attention-Deficit/Hyperactivity Disorder (ADHD) or any other condition. The content is not a substitute for professional evaluation, diagnosis, or treatment by a licensed physician, psychologist, or mental health provider.</li>
                  <li>If you believe you may have a medical or psychological condition, please consult a licensed healthcare provider.</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">2. Information We Collect</h2>
                <div className="space-y-4">
                  <div>
                    <h3 className="font-medium text-gray-800 mb-2">A. Personal Information (provided voluntarily by users):</h3>
                    <ul className="list-disc list-inside space-y-1">
                      <li>Full name and email address (for account registration and communication)</li>
                      <li>Age and region (to comply with legal consent requirements)</li>
                      <li>Assessment responses and game interaction data</li>
                    </ul>
                  </div>
                  
                  <div>
                    <h3 className="font-medium text-gray-800 mb-2">B. Technical Information (automatically collected):</h3>
                    <ul className="list-disc list-inside space-y-1">
                      <li>IP address, browser type, device type</li>
                      <li>Session timestamps and page interactions</li>
                      <li>Cookies and usage analytics</li>
                    </ul>
                  </div>
                </div>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">3. How We Use Your Information</h2>
                <p className="mb-4">We process data only as necessary to:</p>
                <ul className="list-disc list-inside space-y-2">
                  <li>Deliver and personalize user experience and feedback</li>
                  <li>Inform users of their results and encourage appropriate follow-up (non-clinical)</li>
                  <li>Improve the functionality, design, and reliability of our tools</li>
                  <li>Enforce platform security, detect abuse, and comply with applicable laws</li>
                  <li>Communicate essential updates related to your account</li>
                </ul>
                <p className="mt-4 text-sm text-gray-600">
                  All usage is subject to strict data minimization and purpose limitation standards.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">4. Data Security</h2>
                <p className="mb-4">We implement industry-leading safeguards to protect user information, including:</p>
                <ul className="list-disc list-inside space-y-2">
                  <li>End-to-end encryption</li>
                  <li>Secure server infrastructure (HTTPS, firewalls, and physical security)</li>
                  <li>Role-based access controls</li>
                  <li>Regular internal audits and vulnerability scans</li>
                </ul>
                <div className="bg-blue-50 border border-blue-200 p-4 rounded-lg mt-4">
                  <p className="text-blue-800">
                    <strong>Note:</strong> Despite best efforts, no digital system is completely immune to risk. By using the Platform, you acknowledge this inherent limitation and accept that no absolute guarantee can be provided.
                  </p>
                </div>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">5. Information Sharing and Disclosure</h2>
                <p className="mb-4">We do not sell, rent, or trade personal data. We may disclose user information only under the following strictly limited circumstances:</p>
                <ul className="list-disc list-inside space-y-2">
                  <li>With the user's explicit, informed consent</li>
                  <li>To comply with legal obligations, subpoenas, or court orders</li>
                  <li>When necessary to protect the rights, safety, or property of users, staff, or the public</li>
                  <li>For research or product improvement in fully anonymized and aggregated form only</li>
                </ul>
                <p className="mt-4 text-sm text-gray-600">
                  All disclosures are reviewed for legal necessity and minimized in scope.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">6. Legal Basis for Processing (For GDPR Users)</h2>
                <p className="mb-4">If you are located in the European Economic Area, we process your personal data under the following legal bases:</p>
                <ul className="list-disc list-inside space-y-2">
                  <li>Consent (Article 6(1)(a) GDPR)</li>
                  <li>Contractual necessity (Article 6(1)(b))</li>
                  <li>Compliance with legal obligations (Article 6(1)(c))</li>
                  <li>Legitimate interests (Article 6(1)(f)), such as platform security and educational research, unless overridden by your privacy rights</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">7. Your Privacy Rights</h2>
                <p className="mb-4">Subject to jurisdiction, you may exercise the following rights:</p>
                <ul className="list-disc list-inside space-y-2">
                  <li><strong>Access:</strong> Request a copy of your personal data</li>
                  <li><strong>Rectification:</strong> Request corrections to inaccurate or incomplete data</li>
                  <li><strong>Erasure:</strong> Request deletion of your account and associated data</li>
                  <li><strong>Objection/Restriction:</strong> Limit or object to certain types of data processing</li>
                  <li><strong>Portability:</strong> Request export of your data in a readable format</li>
                  <li><strong>Withdraw Consent:</strong> Revoke your consent at any time without affecting past lawful processing</li>
                </ul>
                <p className="mt-4 text-sm text-gray-600">
                  To exercise your rights, email us at privacy@adhdassessment.com. Requests are addressed within the legally required period.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">8. Data Retention</h2>
                <p className="mb-4">We retain personal data only as long as:</p>
                <ul className="list-disc list-inside space-y-2">
                  <li>Necessary to provide services</li>
                  <li>Required by law (e.g., audit logs)</li>
                  <li>Consented to by the user</li>
                </ul>
                <p className="mt-4">
                  When retention is no longer required, data is securely deleted or anonymized in accordance with industry best practices.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">9. Cookies and Tracking Technologies</h2>
                <p className="mb-4">We use cookies and similar technologies for:</p>
                <ul className="list-disc list-inside space-y-2">
                  <li>Session management</li>
                  <li>Platform performance analysis</li>
                  <li>Feature optimization and user preferences</li>
                </ul>
                <p className="mt-4">
                  You may manage cookie settings through your browser or reject optional analytics cookies via in-app options (where available).
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">10. Children's Privacy</h2>
                <div className="bg-yellow-50 border border-yellow-200 p-4 rounded-lg mb-4">
                  <p className="text-yellow-800">
                    <strong>Important:</strong> We do not knowingly collect personal information from children under 13 years of age without verifiable parental consent. Users under 18 must have parental or guardian permission to use the Platform.
                  </p>
                </div>
                <p>
                  If you believe a minor has submitted personal information without appropriate consent, please contact us at privacy@adhdassessment.com for prompt removal.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">11. International Data Transfers</h2>
                <p>
                  Our servers may be located in jurisdictions outside your home country. By using the Platform, you acknowledge and consent to the transfer of your data internationally. We use Standard Contractual Clauses and other approved mechanisms where applicable to safeguard international data transfers under GDPR and similar frameworks.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">12. Limitation of Liability</h2>
                <div className="bg-red-50 border border-red-200 p-4 rounded-lg mb-4">
                  <p className="text-red-800">
                    <strong>Important Disclaimer:</strong> To the fullest extent permitted by law:
                  </p>
                </div>
                <ul className="list-disc list-inside space-y-2">
                  <li>The Platform, its developers, and its affiliates shall not be liable for any direct, indirect, incidental, or consequential damages arising from the use or misuse of the Platform or reliance on any content or output generated.</li>
                  <li>Use of this Platform does not establish a provider-patient relationship.</li>
                  <li>All users agree to hold harmless and indemnify the Platform and its operators from any claims, legal actions, or disputes resulting from use of the Platform or reliance on its content.</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">13. Policy Updates</h2>
                <p>
                  We reserve the right to update this Policy to reflect legal, technological, or operational changes. Users will be notified of significant changes via email or in-app notice. Continued use of the Platform after such notice constitutes acceptance of the updated terms.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-xl font-semibold text-gray-900 mb-4">14. Contact Us</h2>
                <p className="mb-4">
                  To ask questions or submit requests related to this Policy or your data rights, contact:
                </p>
                <div className="mt-4 space-y-2">
                  <p>
                    <strong>Email:</strong> 
                    <a href="mailto:privacy@adhdassessment.com" className="text-darkforest-700 hover:text-darkforest-800 underline ml-2">
                      privacy@adhdassessment.com
                    </a>
                  </p>
                  <p>
                    <strong>Data Protection Officer:</strong> 
                    <a href="mailto:dpo@adhdassessment.com" className="text-darkforest-700 hover:text-darkforest-800 underline ml-2">
                      dpo@adhdassessment.com
                    </a>
                  </p>
                </div>
              </section>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default PrivacyPage; 